version: '3'
services:
  db:
    image: postgres
    volumes:
      - $PWD/pgmaster/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "pass"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/usr/src/dm_rest
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq

    command: >
      sh -c "pip install --upgrade pip &&
        pip install pika &&
        python monitor.py &&
        python manage.py runserver 0.0.0.0:8000"
    
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672

volumes:
  poster_data: